# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.12.3                    # https://pyreadiness.org/3.10
  - pip=24.0                        # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0         # https://pypi.org/project/robocorp-truststore/
  - webdriver_manager
  - pip:
      - robotframework==6.1.1
      - selenium==4.15.2
      - robotframework-seleniumlibrary==6.2.0
      - robotframework-appiumlibrary==2.0.0
      - robotframework-pabot==2.16.0

